default: &default
  adapter: postgresql
  pool: 5
  timeout: 10000
  encoding: unicode

development:
  <<: *default
  database: ThisPresntMoment_development

test:
  <<: *default
  database: ThisPresntMoment_test

production:
  <<: *default
  database: ThisPresntMoment_production
